### ISSUE TITLE
Empty values from time to time

### ISSUE THREAD

**Issue by VDRainer** [FL550/dwd_weather#10]
## Version of home_assistant

0.116.1

## Version of the custom_component

v1.1.8

## Describe the bug
Since last [update](https://github.com/FL550/dwd_weather/issues/9) the weather values are empty from time to time.

![Auswahl_403](https://user-images.githubusercontent.com/26381449/95518346-22ad7d80-09c3-11eb-863c-64b8d633229d.png)

## Debug log

```text

2020-10-08 23:54:19 ERROR (MainThread) [custom_components.dwd_weather] Unexpected error fetching DWD Weather Coordinator for Wuerzburg data: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/srv/ha/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 143, in async_refresh
    self.data = await self._async_update_data()
  File "/srv/ha/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 131, in _async_update_data
    return await self.update_method()
  File "/home/homeassi/.homeassistant/custom_components/dwd_weather/connector.py", line 51, in async_update
    return await self._hass.async_add_executor_job(self._update)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassi/.homeassistant/custom_components/dwd_weather/connector.py", line 99, in _update
    ATTR_FORECAST_TEMP: int(round(temp_max, 0)),
TypeError: type NoneType doesn't define __round__ method

```

**Comment by FL550** [comment]
Thanks for reporting the issue. I fixed this in [v1.1.9](https://github.com/FL550/dwd_weather/tree/v1.1.9).

**Comment by VDRainer** [comment]
Thanks for the fast fix!

**Comment by FL550** [comment]
Danke für die regelmäßigen Inputs 😊
