### ISSUE TITLE
unknown locale: en_DE when adding new station

### ISSUE THREAD

**Issue by bunnu** [FL550/dwd_weather#102]
## Version of home_assistant
Home Assistant 2023.10.5

## Version of the custom_component
2.0.8 (issue occures with 2.0.9 too)

## Describe the bug
After adding a new weather station, the integration tries to initialize it. The UI indicates, that something went wrong and a retry will be initiated. 

![image](https://github.com/FL550/dwd_weather/assets/5147219/dbc92498-57c0-4f70-853c-30604c5fc780)
Even after retry, the integration fails to initialize the new station.

To be able to reproduce the issue, you need to set your country and language in Home Assistant to Germany and English.

![image](https://github.com/FL550/dwd_weather/assets/5147219/de61858d-6330-46bb-a180-9b2647c8f5d0)

## Log

```text

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dwd_weather
Source: helpers/update_coordinator.py:290
Integration: Deutscher Wetterdienst (documentation, issues)
First occurred: 15:58:39 (4 occurrences)
Last logged: 15:59:18

Unexpected error fetching DWD Weather Coordinator for Q879 data: unknown locale: en_DE
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwd_weather/connector.py", line 57, in async_update
    return await self._hass.async_add_executor_job(self._update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwd_weather/connector.py", line 64, in _update
    self.dwd_weather.update(
  File "/config/deps/lib/python3.11/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 549, in update
    self.download_latest_kml(self.station_id, force_hourly)
  File "/config/deps/lib/python3.11/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 799, in download_latest_kml
    self.parse_kml(kml, force_hourly)
  File "/config/deps/lib/python3.11/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 577, in parse_kml
    issue_time_new = self.parse_issue_time(tree)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 640, in parse_issue_time
    time.strptime(
  File "/usr/local/lib/python3.11/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 322, in _strptime
    if (_getlang() != locale_time.lang or
        ^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 28, in _getlang
    return locale.getlocale(locale.LC_TIME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/locale.py", line 609, in getlocale
    return _parse_localename(localename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/locale.py", line 511, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en_DE


```

**Comment by FL550** [comment]
This seems like a system related problem as you have a mixed locale which as far as I understand isn't valid. Can you please try the solutions for a similar problem with kde: https://askubuntu.com/questions/710955/how-to-fix-en-de-utf-8-locales-warnings/710956#710956

**Comment by FL550** [comment]
I adjusted the parsing, so hopefully it will now work without a change at your side.

**Comment by bunnu** [comment]
Thank you. It's working now. Just out of curiosity: Can you link the commit which fixed the issue?

**Comment by FL550** [comment]
I changed the date parsing to a non-standard library which is not dependent on the locale: https://github.com/FL550/simple_dwd_weatherforecast/commit/bbf1ea6d35b0612c3eddcefa919fc61ad2fcc6d2
