### ISSUE TITLE
KeyError: 'weather_interval' in 1.2.0

### ISSUE THREAD

**Issue by VDRainer** [FL550/dwd_weather#14]
## Version of home_assistant

2021.3.0b3

## Version of the custom_component

1.2.0

## Describe the bug
Integration doesn't load, looks like missing `weather_interval`, but how to add it?

## Debug log

```text

2021-02-27 18:18:52 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wuerzburg for dwd_weather
Traceback (most recent call last):
  File "/srv/ha/lib/python3.8/site-packages/homeassistant/config_entries.py", line 251, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassi/.homeassistant/custom_components/dwd_weather/__init__.py", line 40, in async_setup_entry
    time_window = entry.data[CONF_WEATHER_INTERVAL]
KeyError: 'weather_interval'

```

**Comment by FL550** [comment]
Thanks for the report, I changed the update info to inform others prior to updating.

I added a new configuration option and I don't know how to keep backwards compability with this. Sorry for the inconvenience, you have to remove the entity and re-add it.

**Comment by VDRainer** [comment]
> you have to remove the entity and re-add it.

Good to know.
Thanks for your quick response and for this integration.
