### ISSUE TITLE
Atfer Update to 2.1.20: Integration no more working

### ISSUE THREAD

**Issue by ignazhabibi** [FL550/dwd_weather#164]
## Version of home_assistant
2024.10.4

## Version of the custom_component
2.1.20

## Describe the bug
After Updating dwd via HACS to 2.1.20 and restart the integration did not load anymore. See log below

```text

Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 10:14:16 (1 Vorkommnisse)
Zuletzt protokolliert: 10:14:16

Setup failed for custom integration 'dwd_weather': Unable to import component: No module named 'homeassistant.core_config'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 8, in <module>
    from homeassistant.core_config import Config
ModuleNotFoundError: No module named 'homeassistant.core_config'


```

**Comment by wetty** [comment]
Same Problem here

**Comment by HACucoo** [comment]
Same here

**Comment by z-master42** [comment]
I think the minimum HA version for 2.1.20 is 2024.11.

**Comment by ignazhabibi** [comment]
> I think the minimum HA version for 2.1.20 is 2024.11. See #162.

And why is this Update offered to me with a changelog of „small code changes“ when it is complety breaking the integration?

**Comment by route662** [comment]
Same here

**Comment by Benne007** [comment]
Ich habe das gleiche Problem

**Comment by raveit65** [comment]
Same issue here with berlin-tempelhof weather station.

**Comment by allroy7** [comment]
Same problem

**Comment by raveit65** [comment]
> I think the minimum HA version for 2.1.20 is 2024.11. See #162.

This  is bad. I prefer to update HA end of the month to avoid update pain.
How can downgrade dwd-weather?
Replacing files in /homeassistant/custom_components/dwd_weather with last working version?

**Comment by z-master42** [comment]
> > I think the minimum HA version for 2.1.20 is 2024.11. See #162.
> 
> This  is bad. I prefer to update HA end of the month to avoid update pain.
> How can downgrade dwd-weather?
> Replacing files in /homeassistant/custom_components/dwd_weather with last working version?

Simply download it again and select the previous version.

**Comment by Wiz0r** [comment]
Same here

**Comment by Marukiba** [comment]
Same here

**Comment by lifecooler** [comment]
Also the same

**Comment by raveit65** [comment]
> > > I think the minimum HA version for 2.1.20 is 2024.11. See #162.
> > 
> > 
> > This  is bad. I prefer to update HA end of the month to avoid update pain.
> > How can downgrade dwd-weather?
> > Replacing files in /homeassistant/custom_components/dwd_weather with last working version?
> 
> Simply download it again and select the previous version.

Thanks, downgrading to v2.1.19 fixes the issue with HA 2024.10.4. Nice downgrade feature in HACS :)

**Comment by D3NY75** [comment]
Geht bei mir auch nicht mehr! :-(

**Comment by saschaludwig** [comment]
Same here, broken since last update.

```log
Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 13:25:49 (1 Vorkommnisse)
Zuletzt protokolliert: 13:25:49

Setup failed for custom integration 'dwd_weather': Unable to import component: No module named 'homeassistant.core_config'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 8, in <module>
    from homeassistant.core_config import Config
ModuleNotFoundError: No module named 'homeassistant.core_config'

```

**Comment by saschaludwig** [comment]
As the code states, the latest change should be compatible with at least HA 2024.06.1, which isn't true:

https://github.com/FL550/dwd_weather/blob/21b67909ddd42ebc92672ee3e19fb4ba6e72d894/hacs.json#L3

**Comment by FL550** [comment]
@z-master42 Thanks for pinging me. 

Sorry for the hiccup with the update. I changed the min required version at the wrong part in the code. I just released a new version which reverts the changes and will be the last available version for HA versions below 2024.11.

**Comment by jpawlowski** [comment]
https://github.com/FL550/dwd_weather/releases/tag/v2.1.21

**Comment by FL550** [comment]
This is now fixed. Thank you all for reporting here!
