### ISSUE TITLE
500 Server error got into trouble 

### ISSUE THREAD

**Issue by baloo-gh** [FL550/dwd_weather#170]
## Version of home_assistant
2024.11.0

## Version of the custom_component
v2.1.22
v2.1.21

## Describe the bug
Cannot start integration assistant. Stops with popup box saying "500 internal server error, server got itself into trouble"

## Debug log

2024-11-07 05:49:35.206 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package simple_dwd_weatherforecast==2.1.10: error: Failed to prepare distributions
  Caused by: Failed to download and build `stream-unzip==0.0.97`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
[stdout]
Running `maturin pep517 build-wheel -i /tmp/.tmpwv9fXx/builds-v0/.tmp6pPRnL/bin/python --compatibility off`
[stderr]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/tmp/.tmpwv9fXx/builds-v0/.tmp6pPRnL/lib/python3.12/site-packages/maturin/__init__.py", line 119, in build_wheel
    return _build_wheel(wheel_directory, config_settings, metadata_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpwv9fXx/builds-v0/.tmp6pPRnL/lib/python3.12/site-packages/maturin/__init__.py", line 100, in _build_wheel
    result = subprocess.run(command, stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'maturin'
2024-11-07 05:49:36.174 ERROR (MainThread) [reolink_aio.baichuan.baichuan] Baichuan host 192.168.178.87: lost event subscription
2024-11-07 05:49:38.846 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package simple_dwd_weatherforecast==2.1.10: error: Failed to prepare distributions
  Caused by: Failed to download and build `stream-unzip==0.0.97`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
[stdout]
Running `maturin pep517 build-wheel -i /tmp/.tmpW9JGKl/builds-v0/.tmpU30Rm5/bin/python --compatibility off`
[stderr]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/tmp/.tmpW9JGKl/builds-v0/.tmpU30Rm5/lib/python3.12/site-packages/maturin/__init__.py", line 119, in build_wheel
    return _build_wheel(wheel_directory, config_settings, metadata_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpW9JGKl/builds-v0/.tmpU30Rm5/lib/python3.12/site-packages/maturin/__init__.py", line 100, in _build_wheel
    result = subprocess.run(command, stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'maturin'
2024-11-07 05:49:42.238 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package simple_dwd_weatherforecast==2.1.10: error: Failed to prepare distributions
  Caused by: Failed to download and build `stream-unzip==0.0.97`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
[stdout]
Running `maturin pep517 build-wheel -i /tmp/.tmporydVs/builds-v0/.tmpMRSIZa/bin/python --compatibility off`
[stderr]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/tmp/.tmporydVs/builds-v0/.tmpMRSIZa/lib/python3.12/site-packages/maturin/__init__.py", line 119, in build_wheel
    return _build_wheel(wheel_directory, config_settings, metadata_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmporydVs/builds-v0/.tmpMRSIZa/lib/python3.12/site-packages/maturin/__init__.py", line 100, in _build_wheel
    result = subprocess.run(command, stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'maturin'
2024-11-07 05:49:45.766 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package stream-unzip==0.0.95: error: Failed to prepare distributions
  Caused by: Failed to download and build `stream-inflate==0.0.40`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)
[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/tmp/.tmpPp1BC9/builds-v0/.tmpCJfuDn/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpPp1BC9/builds-v0/.tmpCJfuDn/lib/python3.12/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
    self.run_setup()
  File "/tmp/.tmpPp1BC9/builds-v0/.tmpCJfuDn/lib/python3.12/site-packages/setuptools/build_meta.py", line 319, in run_setup
    exec(code, locals())
  File "<string>", line 3, in <module>
  File "/tmp/.tmpPp1BC9/builds-v0/.tmpCJfuDn/lib/python3.12/site-packages/Cython/Build/__init__.py", line 1, in <module>
    from .Dependencies import cythonize
  File "/tmp/.tmpPp1BC9/builds-v0/.tmpCJfuDn/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 42, in <module>
    from .. import Utils
ImportError: Error loading shared library /tmp/.tmpPp1BC9/builds-v0/.tmpCJfuDn/lib/python3.12/site-packages/Cython/Utils.cpython-312-arm-linux-musleabihf.so: Operation not permitted
2024-11-07 05:49:49.337 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package stream-unzip==0.0.95: error: Failed to prepare distributions
  Caused by: Failed to download and build `stream-inflate==0.0.40`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)
[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/tmp/.tmpTlrvqH/builds-v0/.tmp0P7A6c/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpTlrvqH/builds-v0/.tmp0P7A6c/lib/python3.12/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
    self.run_setup()
  File "/tmp/.tmpTlrvqH/builds-v0/.tmp0P7A6c/lib/python3.12/site-packages/setuptools/build_meta.py", line 319, in run_setup
    exec(code, locals())
  File "<string>", line 3, in <module>
  File "/tmp/.tmpTlrvqH/builds-v0/.tmp0P7A6c/lib/python3.12/site-packages/Cython/Build/__init__.py", line 1, in <module>
    from .Dependencies import cythonize
  File "/tmp/.tmpTlrvqH/builds-v0/.tmp0P7A6c/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 42, in <module>
    from .. import Utils
ImportError: Error loading shared library /tmp/.tmpTlrvqH/builds-v0/.tmp0P7A6c/lib/python3.12/site-packages/Cython/Utils.cpython-312-arm-linux-musleabihf.so: Operation not permitted
2024-11-07 05:49:52.727 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package stream-unzip==0.0.95: error: Failed to prepare distributions
  Caused by: Failed to download and build `stream-inflate==0.0.40`
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)
[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/tmp/.tmpcQAkSQ/builds-v0/.tmpq7Ds98/lib/python3.12/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.tmpcQAkSQ/builds-v0/.tmpq7Ds98/lib/python3.12/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
    self.run_setup()
  File "/tmp/.tmpcQAkSQ/builds-v0/.tmpq7Ds98/lib/python3.12/site-packages/setuptools/build_meta.py", line 319, in run_setup
    exec(code, locals())
  File "<string>", line 3, in <module>
  File "/tmp/.tmpcQAkSQ/builds-v0/.tmpq7Ds98/lib/python3.12/site-packages/Cython/Build/__init__.py", line 1, in <module>
    from .Dependencies import cythonize
  File "/tmp/.tmpcQAkSQ/builds-v0/.tmpq7Ds98/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 42, in <module>
    from .. import Utils
ImportError: Error loading shared library /tmp/.tmpcQAkSQ/builds-v0/.tmpq7Ds98/lib/python3.12/site-packages/Cython/Utils.cpython-312-arm-linux-musleabihf.so: Operation not permitted
2024-11-07 05:49:52.731 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1326, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1518, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3246, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3223, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for dwd_weather not found: ['stream-unzip==0.0.95', 'simple_dwd_weatherforecast==2.1.10'].

**Comment by FL550** [comment]
@baloo-gh Can you please format the output?

**Comment by baloo-gh** [comment]
> @baloo-gh Can you please format the output?

@FL550 sorry for that, I was doing that from my mobile which didnt work out properly. Hope this is better readable now.

**Comment by FL550** [comment]
@baloo-gh Thanks for the formatting. What system and version do you use? Containerized or HAOS?

**Comment by baloo-gh** [comment]
Thanks! It is HAOS with the following details:

Core 2024.11.0 
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.0

On the core version: I also had the issue on the 2024.10.X versions - I just was not posting them as I saw a couple of issues you had resolved over the past 2 weeks and had hoped that mine may be resolved through those as well with the latest version you had posted requiring 2024.11.X.

**Comment by FL550** [comment]
Thanks for the info. Can you please install [v2.1.23](https://github.com/FL550/dwd_weather/releases/tag/v2.1.23) and check if this still occurs? You have to enable pre-releases in HACS for the installation.

**Comment by baloo-gh** [comment]
Thanks for the hard work on a weekend! I just tried, yet unfortunately it fails again with the same error message. Here is the corresponding log:

Logger: homeassistant.util.package
Quelle: util/package.py:152
Erstmals aufgetreten: 17:04:45 (3 Vorkommnisse)
Zuletzt protokolliert: 17:04:54

Unable to install package simple_dwd_weatherforecast==2.1.11: error: Failed to prepare distributions Caused by: Failed to download and build `stream-unzip==0.0.97` Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1) [stdout] Running `maturin pep517 build-wheel -i /tmp/.tmpjgoqh5/builds-v0/.tmpnzYdkX/bin/python --compatibility off` [stderr] Traceback (most recent call last): File "<string>", line 11, in <module> File "/tmp/.tmpjgoqh5/builds-v0/.tmpnzYdkX/lib/python3.12/site-packages/maturin/__init__.py", line 119, in build_wheel return _build_wheel(wheel_directory, config_settings, metadata_directory) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmpjgoqh5/builds-v0/.tmpnzYdkX/lib/python3.12/site-packages/maturin/__init__.py", line 100, in _build_wheel result = subprocess.run(command, stdout=subprocess.PIPE) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 548, in run with Popen(*popenargs, **kwargs) as process: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: 'maturin'
Unable to install package simple_dwd_weatherforecast==2.1.11: error: Failed to prepare distributions Caused by: Failed to download and build `stream-unzip==0.0.97` Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1) [stdout] Running `maturin pep517 build-wheel -i /tmp/.tmpH6aMdK/builds-v0/.tmp1XNA22/bin/python --compatibility off` [stderr] Traceback (most recent call last): File "<string>", line 11, in <module> File "/tmp/.tmpH6aMdK/builds-v0/.tmp1XNA22/lib/python3.12/site-packages/maturin/__init__.py", line 119, in build_wheel return _build_wheel(wheel_directory, config_settings, metadata_directory) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmpH6aMdK/builds-v0/.tmp1XNA22/lib/python3.12/site-packages/maturin/__init__.py", line 100, in _build_wheel result = subprocess.run(command, stdout=subprocess.PIPE) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 548, in run with Popen(*popenargs, **kwargs) as process: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: 'maturin'
Unable to install package simple_dwd_weatherforecast==2.1.11: error: Failed to prepare distributions Caused by: Failed to download and build `stream-unzip==0.0.97` Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1) [stdout] Running `maturin pep517 build-wheel -i /tmp/.tmpJHual1/builds-v0/.tmpM6yKRv/bin/python --compatibility off` [stderr] Traceback (most recent call last): File "<string>", line 11, in <module> File "/tmp/.tmpJHual1/builds-v0/.tmpM6yKRv/lib/python3.12/site-packages/maturin/__init__.py", line 119, in build_wheel return _build_wheel(wheel_directory, config_settings, metadata_directory) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmpJHual1/builds-v0/.tmpM6yKRv/lib/python3.12/site-packages/maturin/__init__.py", line 100, in _build_wheel result = subprocess.run(command, stdout=subprocess.PIPE) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 548, in run with Popen(*popenargs, **kwargs) as process: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: 'maturin'

**Comment by FL550** [comment]
@baloo-gh Sorry to bother you again, but I need more information from you. I'm unable to reproduce this, as in a clean ubuntu docker image, which HA core is based on, it installs without issues. So I can only guess it's related to the device you are using. Are you using a RPI to host HA?

**Comment by baloo-gh** [comment]
Thanks a lot for your patience and persistance in trying to figure out what might cause this. To your question:

- HAOS running on a Pi4. Running buttery smooth since 2020 (on a SSD, not a SD card).
- Running within HACS 15 custom integrations, all without any issues.
- Have been running your DWD integration successfully since at least 2 years. Have been updating always without any issues.

About 2-3 weeks ago, I encounterd the same issue as in [https://github.com/FL550/dwd_weather/issues/157](url) once the HA Core was updated to 2024.11.0. I saw you are working on it and once you published the fix for it, I updated the integration. Since them I am having this strange 500 server issue.

Looks I am the only one right now getting the error with your integration. Howevery many custom or base integration of HA eventually suffer from that in some installations. Usually being a dependencies issue. I tested today three versions of your integration, and the error logs seem to point into the direction as well:
- v2.1.21: homeassistant.requirements.RequirementsNotFound: Requirements for dwd_weather not found: ['stream-unzip==0.0.95', 'simple_dwd_weatherforecast==2.1.10']
- v2.1.22: homeassistant.requirements.RequirementsNotFound: Requirements for dwd_weather not found: ['simple_dwd_weatherforecast==2.1.10', 'stream-unzip==0.0.95']
- v2.1.23: homeassistant.requirements.RequirementsNotFound: Requirements for dwd_weather not found: ['simple_dwd_weatherforecast==2.1.11']

So with v2.1.23 one of the two issues has been addressed (stream-unzip), while the requirements for simple_dwd_weatherforecast was not yet. When I look into the logs (based on v2.1.23 being installed), I get:

Unable to install package simple_dwd_weatherforecast==2.1.11: error: Failed to prepare distributions Caused by: Failed to download and build `stream-unzip==0.0.97` Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1) [stdout] Running `maturin pep517 build-wheel -i /tmp/.tmphNwKvo/builds-v0/.tmpxNeUqS/bin/python --compatibility off` [stderr] Traceback (most recent call last): File "<string>", line 11, in <module> File "/tmp/.tmphNwKvo/builds-v0/.tmpxNeUqS/lib/python3.12/site-packages/maturin/__init__.py", line 119, in build_wheel return _build_wheel(wheel_directory, config_settings, metadata_directory) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmphNwKvo/builds-v0/.tmpxNeUqS/lib/python3.12/site-packages/maturin/__init__.py", line 100, in _build_wheel result = subprocess.run(command, stdout=subprocess.PIPE) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 548, in run with Popen(*popenargs, **kwargs) as process: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: 'maturin'

I even went into a copy of .storage to see whether there are any dwd text entries in the registry or core config which may lead to this, but couln`t find anything which should not be there. 

If I continue to be the only one with that issue, then I will wait for a couple of future releases in the hope that eventually things will start to work again. In the meantime I will try to find a way of sourcing the relevant data I need in a different way. Thanks for this super integration, it is a great piece of work and I hope that eventually I can start using it again!

**Comment by FL550** [comment]
@baloo-gh Ok then the issue lies within the ARM architecture of the RPI and I'll try my best in fixing this. See also #161 as this is the same problem.

Regarding this: `[stream-zip](v2.1.23: homeassistant.requirements.RequirementsNotFound: Requirements for dwd_weather not found: ['simple_dwd_weatherforecast==2.1.11'])` This is a caching issue of your mirror as this package was released by me [two days ago](https://pypi.org/project/simple-dwd-weatherforecast/#history).

**Comment by FL550** [comment]
@baloo-gh Can you please check if you have a file /etc/pip.conf on your system with the contents

[global]
extra-index-url=https://www.piwheels.org/simple
Taken from [here](https://www.piwheels.org/faq.html).

**Comment by baloo-gh** [comment]
Sure. I guess you refer to the instance where HAOS is installed on my RPI? That one reads like this:

[global]
disable-pip-version-check = true
extra-index-url = https://wheels.home-assistant.io/musllinux-index/
no-cache-dir = false
prefer-binary = true

**Comment by FL550** [comment]
Interesting! On the piweels package index there is everything available and precompiled. I have to further investigate this.

**Comment by FL550** [comment]
I think I found a solution: https://github.com/home-assistant/wheels-custom-integrations

I'll look further into this tomorrow..

**Comment by baloo-gh** [comment]
Super, thank you already now!

**Comment by FL550** [comment]
@baloo-gh Can you please post the result of this command from within the HA container:

`python3 -c 'import pip._internal.utils.compatibility_tags; print(pip._internal.utils.compatibility_tags.get_supported())'`

**Comment by baloo-gh** [comment]
Closing this one here, as this is likely linked to the very same root cause identified by @FL550 in [https://github.com/FL550/dwd_weather/issues/161](url)

**Comment by baloo-gh** [comment]
Closing this one here, as this is likely linked to the very same root cause identified by @FL550 in [https://github.com/FL550/dwd_weather/issues/161](https://github.com/FL550/dwd_weather/issues/url)

**Comment by FL550** [comment]
@StarPicard Please open a new issue and provide me the complete error message.
