### ISSUE TITLE
"500 Internal Server Error Server got itself in trouble" when installing

### ISSUE THREAD

**Issue by airhead1234** [FL550/dwd_weather#174]
## Version of home_assistant
2024.11.3

## Version of the custom_component
2.1.24

## Describe the bug
After installing the latest version of the component via HACS, adding the integration in Home Assistants leads to a "500 Internal Server Error". I am running Home Assistant in Docker on a Raspberry Pi 4.

## Debug log

```text

2024-11-29 21:50:29.030 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package simple_dwd_weatherforecast==2.1.13: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:29.207 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package simple_dwd_weatherforecast==2.1.13: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:29.388 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package simple_dwd_weatherforecast==2.1.13: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:29.570 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package markdownify==0.6.5: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:29.751 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package markdownify==0.6.5: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:29.966 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package markdownify==0.6.5: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:30.148 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package suntimes==1.1.2: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:30.331 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package suntimes==1.1.2: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:30.516 ERROR (SyncWorker_9) [homeassistant.util.package] Unable to install package suntimes==1.1.2: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 47, in <module>
    _run()
  File "/usr/local/lib/python3.12/site-packages/uv/__main__.py", line 27, in _run
    uv = os.fsdecode(find_uv_bin())
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uv/_find_uv.py", line 36, in find_uv_bin
    raise FileNotFoundError(path)
FileNotFoundError: /home/homeassistant/.local/bin/uv
2024-11-29 21:50:30.518 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1326, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1518, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3268, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3245, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for dwd_weather not found: ['markdownify==0.6.5', 'suntimes==1.1.2', 'simple_dwd_weatherforecast==2.1.13'].

```

**Comment by FL550** [comment]
@airhead1234 Sorry for the late reply. Are you running HA in a container?

**Comment by airhead1234** [comment]
Yes, HA in Docker on a Raspberry Pi 4. Thank you for looking into this.

**Comment by FL550** [comment]
Then it has the same root cause as #175.

**Comment by airhead1234** [comment]
Thank you. I will await a fix in Home Assistant then and hope to be able to use your greate integration again soon.

**Comment by FL550** [comment]
@airhead1234

You might try some of these workarounds:  [home-assistant/core#127966](https://github.com/home-assistant/core/issues/127966) and https://community.home-assistant.io/t/wth-is-going-on-with-docker-container-installs-and-third-party-integrations-that-need-python-modules/806430
