### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Kanecaine** [FL550/dwd_weather#177]
## Version of home_assistant

Version 	core-2024.12.5
Installationstyp 	Home Assistant OS
Entwicklung 	false
Supervisor 	true
Docker 	true
Benutzer 	root
Virtuelle Umgebung 	false
Python-Version 	3.13.0
Betriebssystemfamilie 	Linux
Betriebssystem-Version 	6.6.66-haos
CPU-Architektur 	x86_64

## How are you running home_assistant
I am running HAOS on proxmox

## Version of the custom_component
v2.1.26

## Describe the bug
I recently had the following error in the logs. Otherwise, the integration works without any problems and weather data is retrieved correctly.

## Debug log

```text
Logger: custom_components.dwd_weather
Quelle: helpers/update_coordinator.py:379
Integration: Deutscher Wetterdienst (Dokumentation, Probleme)
Erstmals aufgetreten: 10:40:28 (1 Vorkommnisse)
Zuletzt protokolliert: 10:40:28

Unexpected error fetching DWD Weather Coordinator for 10471 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwd_weather/connector.py", line 129, in async_update
    if await self._hass.async_add_executor_job(self._update):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dwd_weather/connector.py", line 138, in _update
    self.dwd_weather.update(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        force_hourly=self._config[CONF_HOURLY_UPDATE],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
        with_uv=True,
        ^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 674, in update
    self.download_latest_kml(self.station_id, force_hourly)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 1027, in download_latest_kml
    self.parse_kml(kml)
    ~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 707, in parse_kml
    self.loaded_station_name = self.parse_station_name(tree)
                               ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 760, in parse_station_name
    return tree.xpath(
           ~~~~~~~~~~~
        "./kml:Document/kml:Placemark/kml:description", namespaces=self.namespaces
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    )[0].text
    ~^^^
IndexError: list index out of range

```

**Comment by FL550** [comment]
Thanks for reporting!

**Comment by FL550** [comment]
I'll fixed this in the underlaying library and will be included in a next release. Best regards!
