### ISSUE TITLE
Unexpected error fetching DWD Weather Coordinator for amsterdam data: 'Nordholland'

### ISSUE THREAD

**Issue by bakboord4** [FL550/dwd_weather#28]
Host-besturingssysteem | Home Assistant OS 5.13
Supervisor versie | supervisor-2021.04.0

v1.2.10; already present v1.2.9. 

## Describe the bug

Unexpected error fetching DWD Weather Coordinator for amsterdam data: 'Nordholland'

it happens at startup time and continuously creating errors (229 errors in about 24 hrs time)

To me, it looks like closed issue 26 - Saarland
Here is the problem "Nordholland'.  

```text

Logger: custom_components.dwd_weather
Source: custom_components/dwd_weather/connector.py:61 
Integration: Deutscher Wetterdienst (DWD) (documentation, issues) 
First occurred: 9:57:29 (229 occurrences) 
Last logged: 13:45:29

Unexpected error fetching DWD Weather Coordinator for amsterdam data: 'Nordholland'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/dwd_weather/connector.py", line 54, in async_update
    return await self._hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dwd_weather/connector.py", line 61, in _update
    self.dwd_weather.update()
  File "/usr/local/lib/python3.8/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 393, in update
    weather_report = download_weather_report(self.region_codes[self.region])
KeyError: 'Nordholland'

```

**Comment by FL550** [comment]
Yes, you are right. Thanks for the report! I'll fix this as soon as possible!

**Comment by FL550** [comment]
I released a new version, which fixes this error.

**Comment by bakboord4** [comment]
Thank you for your quick response and effort put in to fix the error! 
Installed and DWD functions without the reported error.
I close this issue.
