### ISSUE TITLE
Unable to prepare setup for platform dwd_weather.sensor in HA 0.115.0b0 

### ISSUE THREAD

**Issue by VDRainer** [FL550/dwd_weather#7]
## Version of the custom_component

v1.1.4
## Describe the bug
Seeing the following errors on HA start.
I have not enabled any of the additional sensors and the weather integration seems to work as expected.

## Debug log

```text

2020-09-08 01:57:07 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform dwd_weather.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/srv/ha/lib/python3.8/site-packages/homeassistant/const.py)).
2020-09-08 01:57:07 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform dwd_weather.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/srv/ha/lib/python3.8/site-packages/homeassistant/const.py)).


```

**Comment by FL550** [comment]
Ok, then maybe they removed this from home_assistant. I relased v1.1.5 which fixes this error. Thanks for the issue!

**Comment by S-Przybylski** [comment]
After the update i got this error:
````
2020-09-08 11:56:43 ERROR (MainThread) [homeassistant.components.weather] Error while setting up dwd_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 522, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 144, in state_attributes
    if self.temperature is not None:
  File "/config/custom_components/dwd_weather/weather.py", line 70, in temperature
    return self._connector.get_temperature()
  File "/config/custom_components/dwd_weather/connector.py", line 117, in get_temperature
    self.dwd_weather.get_forecast_data(
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
````

**Comment by S-Przybylski** [comment]
Dear @FL550 could you please check again?

**Comment by FL550** [comment]
I'm on it. I'll write if it's fixed.

**Comment by FL550** [comment]
Should be fixed now. Can you confirm this?

**Comment by S-Przybylski** [comment]
Dear @FL550  the patch 1.1.7 fixed my issue! Thank you very much!

**Comment by FL550** [comment]
Great!
