### ISSUE TITLE
missing the entity for text-based report (Wetterbericht)

### ISSUE THREAD

**Issue by charly166** [FL550/dwd_weather#99]
With one of the updates in the last weeks, the report entity wasn't available anymore. In the meanwhile the entity is there, but always empty. Is there a chance to get this entity back to work? Thanks in advance.

Best regards, Charly

**Comment by FL550** [comment]
Without any information about the station or debug log files, I am unable to help

**Comment by charly166** [comment]
```
Logger: homeassistant
Source: custom_components/dwd_weather/connector.py:258
Integration: Deutscher Wetterdienst ([documentation](https://github.com/FL550/dwd_weather), [issues](https://github.com/FL550/dwd_weather/issues))
First occurred: 24. Oktober 2023 um 15:23:57 (2464 occurrences)
Last logged: 08:27:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/dwd_weather/sensor.py", line 328, in state
    result = self._connector.get_sun_irradiance()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwd_weather/connector.py", line 330, in get_sun_irradiance
    return self.get_weather_value(WeatherDataType.SUN_IRRADIANCE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwd_weather/connector.py", line 258, in get_weather_value
    (next_value - value)
     ~~~~~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

**Comment by FL550** [comment]
Found the issue, there was a typo introduced in one of the last updates. I'll release a new version soon which will fix this.
